# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: PCA_and_friends
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.10
  - conda-forge::r-tidyverse=1.3.1
  - bioconda::eigensoft=7.2.1
  - bioconda::poseidon-trident=0.21.0
  - bioconda::plink=1.90
  - conda-forge::jupyter=1.0.0
  - conda-forge::jupyterlab
  - conda-forge::r-irkernel=1.2
  - conda-forge::r-essentials=4.0
  - conda-forge::rpy2=3.4.5
  - conda-forge::r-remotes=2.4.0
  - conda-forge::r-gridextra=2.3
  - conda-forge::pandas=1.3.3
  - conda-forge::numpy=1.21.2
